---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

## Introduction   

We want to assess whether adding in dye to the standards has an effect on our assay.  

```{r}
stability_dye <- tibble::tribble(
  ~time_point, ~date, ~pm_number, ~operator, ~nsb, 	~sd_nsb, 	~S6,	~S5, 	~S1, 	~Ctl_Low, 	~Ctl_mid, 	~Ctr_High, 	~Nat_Ctrl, ~assay,   ~dye, 
          "Day 0", "9-Nov-21",   9139,  "ST",    58.1,    3.37,    69.6,    275,    40193,     178,      451,      616,    "8.10",   "IL-8",  "no",
         "Day 0",  "9-Nov-21",   9139L, "AD",      56,    4.88,    94.5,    365,    37003,     132,      429,      579,    "5.18",   "IL-8",  "no",
         "Day 0",  "9-Nov-21",   9139L, "JH",    60.6,    4.72,   114.3,    427,    54367,     169,      461,      659,    "7.43",   "IL-8",  "no",
  "Week1  ¯20oC", "17-Nov-21",   9139L, "ST",    60.4,    5.25,    50.9,    205,    28220,     174,      426,      608,   "10.35",   "IL-8",  "no",
  "Week1  ¯80oC", "17-Nov-21",   9139L, "ST",    60.4,    5.25,    46.1,    196,    38404,     183,      461,      635,   "11.00",   "IL-8",  "no",
      "RT 4 hrs", "18-Nov-21",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,   "IL-8",  "no",
      "RT 2 hrs", "18-Nov-21",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,   "IL-8",  "no",
     "RT 90 min", "18-Nov-21",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,   "IL-8",  "no",
     "RT 60 min", "18-Nov-21",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,   "IL-8",  "no",
     "RT 30 min", "18-Nov-21",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,   "IL-8",  "no",
  "Week2  ¯20oC", "23-Nov-21",   9139L, "ST",    53.7,    5.14,    57.5,  225.5,    44858,     232,      612,      813,   "11.66",   "IL-8",  "no",
  "Week2  ¯80oC", "23-Nov-21",   9139L, "ST",    53.7,    5.14,    43.3,  196.3,    45438,     247,      645,      851,   "13.05",   "IL-8",  "no",
  "Week4  ¯20oC",  "8-Dec-21",   9139L, "AD",    79.9,    11.4,   123.6,  431.1,    38873,     178,      557,      805,    "6.13",   "IL-8",  "no",
  "Week4  ¯80oC",  "8-Dec-21",   9139L, "AD",    79.9,    11.4,    83.9,  351.1,    42446,     192,      580,      818,    "7.56",   "IL-8",  "no",
  "Week9  ¯20oC", "11-Jan-22",   9139L, "ST",    56.5,    4.12,    56.5,  290.8,    46247,     235,      597,      798,   "12.21",   "IL-8",  "no",
  "Week9  ¯80oC", "11-Jan-22",   9139L, "ST",    56.5,    4.12,    64.8,  262.5,  45127.8,     239,      618,      834,   "13.45",   "IL-8",  "no",
         "Day 0",     "44509",   9139L, "ST",    58.1,    3.37,    69.6,  274.6,  40193.4,  178.47,   451.22,   615.73,     "8.1",   "IL-8", "yes",
         "Day 0",     "44509",   9139L, "AD",      56,    4.88,    94.5,  365.2,  37003.2,  132.08,   429.03,   579.15,    "5.18",   "IL-8", "yes",
         "Day 0",     "44509",   9139L, "JH",    60.6,    4.72,   114.3,  427.1,  54366.8,  168.88,   461.03,   658.63,    "7.43",   "IL-8", "yes",
  "Week1  ¯20oC",     "44517",   9139L, "ST",    60.4,    5.25,    50.9,  204.9,  28220.1,  174.35,    426.4,   608.13,   "10.35",   "IL-8", "yes",
  "Week1  ¯80oC",     "44517",   9139L, "ST",    60.4,    5.25,    46.1,  196.1,  38404.4,  183.43,   461.29,   634.69,      "11",   "IL-8", "yes",
      "RT 4 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,   "IL-8", "yes",
      "RT 2 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,   "IL-8", "yes",
     "RT 90 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,   "IL-8", "yes",
     "RT 60 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,   "IL-8", "yes",
     "RT 30 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,   "IL-8", "yes",
  "Week2  ¯20oC",     "44523",   9139L, "ST",    53.7,    5.14,    57.5,  225.5,  44857.8,  231.67,    611.5,   812.82,   "11.66",   "IL-8", "yes",
  "Week2  ¯80oC",     "44523",   9139L, "ST",    53.7,    5.14,    43.3,  196.3,    45438,  246.66,   644.82,   851.45,   "13.05",   "IL-8", "yes",
  "Week4  ¯20oC",     "44538",   9139L, "AD",    79.9,    11.4,   123.6,  431.1,  38872.9,  177.79,    557.1,   804.79,    "6.13",   "IL-8", "yes",
  "Week4  ¯80oC",     "44538",   9139L, "AD",    79.9,    11.4,    83.9,  351.1,  42445.9,  191.89,   580.47,   817.68,    "7.56",   "IL-8", "yes",
  "Week9  ¯20oC",     "44572",   9139L, "ST",    56.5,    4.12,    56.5,  290.8,    46247,  234.62,   596.86,   797.91,   "12.21",   "IL-8", "yes",
  "Week9  ¯80oC",     "44572",   9139L, "ST",    56.5,    4.12,    64.8,  262.5,  45127.8,  239.39,   617.56,   834.08,   "13.45",   "IL-8", "yes",
         "Day 0",     "44509",   9139L, "ST",    61.2,   55.31,      59,  177.5,    38101, 1309.94,  3757.34,   4740.2,  "278.11", "MUC-16",  "no",
         "Day 0",     "44509",   9139L, "AD",    60.1,    5.19,    57.9,  219.4,  32151.9, 1245.27,  3987.97,  5156.72,  "208.11", "MUC-16",  "no",
         "Day 0",     "44509",   9139L, "JH",    63.1,    5.55,    98.4,  373.9,  62607.4, 1320.28,  4361.86,  5644.09,  "261.16", "MUC-16",  "no",
  "Week1  ¯20oC",     "44517",   9139L, "ST",    63.8,    6.81,      44,  169.2,  38702.7, 1276.87,  4059.51,  5158.27,  "257.11", "MUC-16",  "no",
  "Week1  ¯80oC",     "44517",   9139L, "ST",    63.3,    7.34,    53.2,  172.4,  40002.9, 1290.01,  3756.86,  4714.79,  "289.54", "MUC-16",  "no",
      "RT 4 hrs",     "44518",   9139L, "JH",    56.9,    5.58,    56.1,  243.6,  39788.8,  1209.5,  4173.55,  5276.66,  "256.78", "MUC-16",  "no",
      "RT 2 hrs",     "44518",   9139L, "JH",    56.9,    5.58,    63.8,  237.1,  40386.6, 1151.71,  4087.55,   5212.6,  "252.55", "MUC-16",  "no",
     "RT 90 min",     "44518",   9139L, "JH",    56.9,    5.58,    67.6,  230.6,  40253.3, 1275.09,  4108.92,  5103.69,  "275.87", "MUC-16",  "no",
     "RT 60 min",     "44518",   9139L, "JH",    56.9,    5.58,    72.3,  301.6,  43200.8, 1050.44,  3493.05,  4362.67,  "220.27", "MUC-16",  "no",
     "RT 30 min",     "44518",   9139L, "JH",    56.9,    5.58,    84.1,  307.6,  46049.6,   968.2,  3283.91,  4135.28,   "207.4", "MUC-16",  "no",
  "Week2  ¯20oC",     "44523",   9139L, "ST",    58.2,    4.62,    49.3,  182.1,  43483.8, 1394.04,   4004.6,  4910.49,  "286.69", "MUC-16",  "no",
  "Week2  ¯80oC",     "44523",   9139L, "ST",    58.2,    4.62,    50.3,  184.8,  44458.3, 1353.69,  4008.43,  4948.38,   "277.7", "MUC-16",  "no",
  "Week4  ¯20oC",     "44538",   9139L, "AD",    62.2,    4.35,    75.8,  280.3,  36616.8, 1290.19,  4432.47,  5683.74,  "219.29", "MUC-16",  "no",
  "Week4  ¯80oC",     "44538",   9139L, "AD",    62.2,    4.35,    77.8,  273.8,  39354.5, 1218.19,  3983.71,  5122.04,  "229.77", "MUC-16",  "no",
  "Week9  ¯20oC",     "44572",   9139L, "ST",    57.8,    4.39,    47.2,  203.7,  44366.2, 1505.53,  4244.13,  5260.71,  "315.55", "MUC-16",  "no",
  "Week9  ¯80oC",     "44572",   9139L, "ST",    57.8,    4.39,      56,  224.7,  45062.2, 1431.57,  4065.32,   5047.6,  "296.61", "MUC-16",  "no",
         "Day 0",     "44509",   9139L, "ST",    61.2,    5.31,    36.3,  147.3,    34827, 1289.25,  3754.41,  4703.82,   "259.9", "MUC-16", "yes",
         "Day 0",     "44509",   9139L, "AD",    60.1,    5.19,    47.9,  200.7,  28837.4, 1255.65,  3865.79,  4863.51,  "202.48", "MUC-16", "yes",
         "Day 0",     "44509",   9139L, "JH",    63.1,    5.55,    78.9,  300.6,    55700,  1376.7,  4329.46,  5559.67,  "280.95", "MUC-16", "yes",
  "Week1  ¯20oC",     "44517",   9139L, "ST",    63.8,    6.81,      40,  139.7,  36004.5,  1379.6,  3685.56,  4501.19,  "311.96", "MUC-16", "yes",
  "Week1  ¯80oC",     "44517",   9139L, "ST",    63.8,    6.81,    25.5,  125.5,  34031.7,  1445.3,  4074.97,  5078.52,  "331.33", "MUC-16", "yes",
      "RT 4 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA, "MUC-16", "yes",
      "RT 2 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA, "MUC-16", "yes",
     "RT 90 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA, "MUC-16", "yes",
     "RT 60 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA, "MUC-16", "yes",
     "RT 30 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA, "MUC-16", "yes",
  "Week2  ¯20oC",     "44523",   9139L, "ST",    58.2,    4.62,    45.8,  163.8,  42450.8, 1546.39,  4458.34,  5468.17,  "320.89", "MUC-16", "yes",
  "Week2  ¯80oC",     "44523",   9139L, "ST",    58.2,    4.62,    17.8,  130.8,  41737.1, 1695.98,  4725.32,  5743.27,  "360.46", "MUC-16", "yes",
  "Week4  ¯20oC",     "44538",   9139L, "AD",    62.2,    4.35,    70.5,  248.3,  35688.8, 1347.56,  4428.92,  5728.37,  "259.35", "MUC-16", "yes",
  "Week4  ¯80oC",     "44538",   9139L, "AD",    62.2,    4.35,    59.5,  228.3,    36147, 1339.74,  4531.72,  5900.13,  "261.48", "MUC-16", "yes",
  "Week9  ¯20oC",     "44572",   9139L, "ST",    57.8,    4.39,    38.7,  174.7,    42028, 1663.06,  4722.34,  5869.18,  "352.16", "MUC-16", "yes",
  "Week9  ¯80oC",     "44572",   9139L, "ST",    57.8,    4.39,    33.7,  171.2,  41412.7, 1727.71,  4886.79,  6060.43,  "362.08", "MUC-16", "yes",
         "Day 0",     "44509",   9139L, "ST",     116,    8.34,    73.7,  197.7,    25043, 5770.88,  8746.17, 11819.59, "3414.31",  "IL1R2",  "no",
         "Day 0",     "44509",   9139L, "AD",   108.2,   12.21,    61.6,  237.6,    24232, 5691.35,  8426.85, 11067.95, "2973.27",  "IL1R2",  "no",
         "Day 0",     "44509",   9139L, "JH",   133.9,    9.45,   105.3,  407.1,  39113.6, 5970.72,  9594.84, 12627.74, "3283.85",  "IL1R2",  "no",
  "Week1  ¯20oC",     "44517",   9139L, "ST",   121.4,    8.25,    52.1,  180.1,  25328.3, 6540.55,  9238.13, 12992.01, "4077.31",  "IL1R2",  "no",
  "Week1  ¯80oC",     "44517",   9139L, "ST",   121.1,    7.82,    49.2,  188.4,  26048.2, 5920.52,  8280.47,  11573.8, "3751.31",  "IL1R2",  "no",
      "RT 4 hrs",     "44518",   9139L, "JH",   109.5,    9.92,    54.8,  258.3,    25468, 5862.07,  9573.43, 12810.34, "3342.37",  "IL1R2",  "no",
      "RT 2 hrs",     "44518",   9139L, "JH",   109.5,    9.92,    54.3,  261.8,  24980.5, 5412.27,  8745.37, 11738.18, "3145.51",  "IL1R2",  "no",
     "RT 90 min",     "44518",   9139L, "JH",   109.5,    9.92,      58,  222.3,  25247.5, 5800.47,  9095.14, 11958.74, "3461.03",  "IL1R2",  "no",
     "RT 60 min",     "44518",   9139L, "JH",   109.5,    9.92,    71.5,  283.5,  25583.8, 4723.44,   7670.3, 10361.14, "2750.62",  "IL1R2",  "no",
     "RT 30 min",     "44518",   9139L, "JH",   109.5,    9.92,   107.5,    313,    27905, 4640.29,  7454.78,  9899.36, "2701.69",  "IL1R2",  "no",
  "Week2  ¯20oC",     "44523",   9139L, "ST",   108.9,    7.58,    45.1,  190.1,  27516.8, 5949.92,  8884.39, 11860.84, "3487.97",  "IL1R2",  "no",
  "Week2  ¯80oC",     "44523",   9139L, "ST",   108.9,    7.58,    51.8,  202.3,  28497.6, 5960.52,  9018.98, 12076.76, "3422.72",  "IL1R2",  "no",
  "Week4  ¯20oC",     "44538",   9139L, "AD",   106.6,    5.32,    82.4,  286.6,  23023.9,  6888.5,  11376.5, 16625.11, "3773.04",  "IL1R2",  "no",
  "Week4  ¯80oC",     "44538",   9139L, "AD",   106.6,    5.32,    91.1,  267.4,  23511.1,  5577.1,  8954.37, 13256.96, "3273.75",  "IL1R2",  "no",
  "Week9  ¯20oC",     "44572",   9139L, "ST",   116.6,    5.42,    52.1,  220.4,  27300.1, 5803.74,  8462.42, 11872.21, "3308.49",  "IL1R2",  "no",
  "Week9  ¯80oC",     "44572",   9139L, "ST",   116.6,    5.42,    66.4,  236.6,  27793.4, 5565.16,  8297.88, 11829.12, "3078.46",  "IL1R2",  "no",
         "Day 0",     "44509",   9139L, "ST",     116,    8.34,    61.5,  249.5,  26691.5, 5694.24,  8550.83, 11421.52, "3362.88",  "IL1R2", "yes",
         "Day 0",     "44509",   9139L, "AD",   108.2,   12.21,    82.1,  312.1,  34876.6, 5448.93,   8120.9, 10732.83, "2810.19",  "IL1R2", "yes",
         "Day 0",     "44509",   9139L, "JH",   133.9,    9.45,   134.6,  453.3,  40785.6, 5837.13,  9392.16, 12422.11, "3236.71",  "IL1R2", "yes",
  "Week1  ¯20oC",     "44517",   9139L, "ST",   121.4,    8.25,    41.1,  211.3,  26088.6, 6167.73,  8786.63, 12565.76, "3841.79",  "IL1R2", "yes",
  "Week1  ¯80oC",     "44517",   9139L, "ST",   121.4,    8.25,    34.1,  176.6,  25769.1, 6357.22,   9111.2, 13144.79,  "3955.9",  "IL1R2", "yes",
      "RT 4 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,  "IL1R2", "yes",
      "RT 2 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,  "IL1R2", "yes",
     "RT 90 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,  "IL1R2", "yes",
     "RT 60 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,  "IL1R2", "yes",
     "RT 30 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,  "IL1R2", "yes",
  "Week2  ¯20oC",     "44523",   9139L, "ST",   108.9,    7.58,    65.1,  263.8,  30452.8, 4966.38,   7328.2,  9646.24, "2926.68",  "IL1R2", "yes",
  "Week2  ¯80oC",     "44523",   9139L, "ST",   108.9,    7.58,    34.1,  189.1,  30249.8, 5496.77,  8198.78, 10860.57, "3212.54",  "IL1R2", "yes",
  "Week4  ¯20oC",     "44538",   9139L, "AD",   106.6,    5.32,   106.6,  347.1,  24989.9, 4467.85,  7289.74, 10933.63, "2574.63",  "IL1R2", "yes",
  "Week4  ¯80oC",     "44538",   9139L, "AD",   106.6,    5.32,    78.6,  302.6,  25001.4, 4541.37,  7525.86, 11380.45,  "2575.7",  "IL1R2", "yes",
  "Week9  ¯20oC",     "44572",   9139L, "ST",   116.6,    5.42,    51.9,  253.6,  29835.9, 4747.78,  7079.44, 10074.89, "2626.25",  "IL1R2", "yes",
  "Week9  ¯80oC",     "44572",   9139L, "ST",   116.6,    5.42,    58.9,  245.1,  29081.9, 4968.92,  7277.98, 10223.92, "2812.75",  "IL1R2", "yes",
         "Day 0",     "44509",   9139L, "ST",   186.2,    8.53,    51.8,    104,  38411.3,  318.56,   712.54,  1036.61,   "45.18",  "FLT3L",  "no",
         "Day 0",     "44509",   9139L, "AD",   181.2,    7.63,    30.8,  113.8,  32471.6,  292.87,   749.71,  1045.28,    "37.4",  "FLT3L",  "no",
         "Day 0",     "44509",   9139L, "JH",   194.8,    6.89,    48.7,    164,  52485.5,  289.98,   718.48,  1098.42,   "39.42",  "FLT3L",  "no",
  "Week1  ¯20oC",     "44517",   9139L, "ST",   186.3,    9.72,    13.8,   91.5,  29383.3,  293.01,   573.69,  1001.68,   "49.84",  "FLT3L",  "no",
  "Week1  ¯80oC",     "44517",   9139L, "ST",   186.3,   10.16,    37.2,  101.7,  34245.4,  251.45,   499.72,      882,   "39.75",  "FLT3L",  "no",
      "RT 4 hrs",     "44518",   9139L, "JH",   173.6,     9.4,    39.9,  116.4,  33010.9,  254.19,   697.88,  1042.98,   "36.39",  "FLT3L",  "no",
      "RT 2 hrs",     "44518",   9139L, "JH",   173.6,     9.4,    32.9,  120.4,  35087.9,  242.77,   657.43,   977.72,   "36.01",  "FLT3L",  "no",
     "RT 90 min",     "44518",   9139L, "JH",   173.6,     9.4,    28.9,  113.9,  32035.9,  256.63,   691.79,  1026.66,   "38.36",  "FLT3L",  "no",
     "RT 60 min",     "44518",   9139L, "JH",   173.6,     9.4,    26.4,  125.4,  36869.9,  219.22,   587.31,   869.67,   "33.54",  "FLT3L",  "no",
     "RT 30 min",     "44518",   9139L, "JH",   173.6,     9.4,    45.9,  119.4,  36939.4,   234.7,   635.31,   944.03,   "34.19",  "FLT3L",  "no",
  "Week2  ¯20oC",     "44523",   9139L, "ST",   186.8,    8.69,     7.5,     82,  34773.2,  324.22,    725.7,  1027.02,   "40.81",  "FLT3L",  "no",
  "Week2  ¯80oC",     "44523",   9139L, "ST",   186.8,    8.69,      21,   82.5,  36322.7,  319.81,   712.18,  1004.86,   "39.84",  "FLT3L",  "no",
  "Week4  ¯20oC",     "44538",   9139L, "AD",   192.3,     8.1,    40.9,  132.9,  27833.2,  305.07,   768.23,   1161.7,   "35.52",  "FLT3L",  "no",
  "Week4  ¯80oC",     "44538",   9139L, "AD",   192.3,     8.1,    41.4,  121.2,  33377.9,  290.17,   695.01,  1027.65,   "37.91",  "FLT3L",  "no",
  "Week9  ¯20oC",     "44572",   9139L, "ST",   188.1,    6.39,    32.9,   97.4,  41775.9,  345.73,   796.01,  1213.72,   "48.55",  "FLT3L",  "no",
  "Week9  ¯80oC",     "44572",   9139L, "ST",   188.1,    6.39,    18.4,   97.9,  44462.2,  321.75,   747.14,  1144.76,   "45.25",  "FLT3L",  "no",
         "Day 0",     "44509",   9139L, "ST",   186.2,    8.53,      29,   91.8,  35955.5,  324.99,   759.57,   1128.7,   "43.12",  "FLT3L", "yes",
         "Day 0",     "44509",   9139L, "AD",   181.2,    7.63,    44.6,  126.1,  32344.3,  252.25,   665.57,   937.76,   "29.81",  "FLT3L", "yes",
         "Day 0",     "44509",   9139L, "JH",   194.8,    6.89,    38.7,  143.5,  44834.7,  293.12,   724.66,  1107.48,    "40.7",  "FLT3L", "yes",
  "Week1  ¯20oC",     "44517",   9139L, "ST",   186.3,    9.72,    29.8,   79.8,    17182,  278.32,    529.3,   901.56,   "50.19",  "FLT3L", "yes",
  "Week1  ¯80oC",     "44517",   9139L, "ST",   186.3,    9.72,      18,   76.3,  28454.8,  291.94,   556.54,   950.35,   "53.01",  "FLT3L", "yes",
      "RT 4 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,  "FLT3L", "yes",
      "RT 2 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,  "FLT3L", "yes",
     "RT 90 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,  "FLT3L", "yes",
     "RT 60 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,  "FLT3L", "yes",
     "RT 30 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,  "FLT3L", "yes",
  "Week2  ¯20oC",     "44523",   9139L, "ST",   186.8,    8.69,    15.7,   85.7,    35661,  327.47,   728.37,  1027.16,   "40.91",  "FLT3L", "yes",
  "Week2  ¯80oC",     "44523",   9139L, "ST",   186.8,    8.69,    11.7,   71.2,  37558.5,  353.77,   756.04,  1047.88,   "48.68",  "FLT3L", "yes",
  "Week4  ¯20oC",     "44538",   9139L, "AD",   192.3,     8.1,    30.7,  141.2,  31673.2,  263.24,   667.93,   1014.4,   "31.37",  "FLT3L", "yes",
  "Week4  ¯80oC",     "44538",   9139L, "AD",   192.3,     8.1,    17.7,  137.2,  37815.2,  289.93,   675.52,   986.64,  "40.52*",  "FLT3L", "yes",
  "Week9  ¯20oC",     "44572",   9139L, "ST",   188.1,    6.39,    19.9,   95.7,  43301.4,  338.04,   774.06,  1177.42,   "48.67",  "FLT3L", "yes",
  "Week9  ¯80oC",     "44572",   9139L, "ST",   188.1,    6.39,    21.2,   99.9,  41967.2,  356.79,   812.98,  1233.24,   "51.56",  "FLT3L", "yes",
         "Day 0",     "44509",   9139L, "ST",      73,    8.09,    40.3,  188.3,  65413.3,  989.53,  2932.48,  3547.49,  "210.65",    "CEA",  "no",
         "Day 0",     "44509",   9139L, "AD",    70.2,    6.75,    60.3,    210,    55652,  995.53,  3091.77,  3909.91,  "184.78",    "CEA",  "no",
         "Day 0",     "44509",   9139L, "JH",    78.3,    6.68,     102,    381,   101811, 1053.04,  3158.31,  3752.65,  "183.04",    "CEA",  "no",
  "Week1  ¯20oC",     "44517",   9139L, "ST",      83,    8.78,    32.8,    156,    64992,  1176.2,  3323.65,  4085.21,  "260.76",    "CEA",  "no",
  "Week1  ¯80oC",     "44517",   9139L, "ST",      83,    8.78,    47.5,  162.8,  68264.5, 1206.34,  3359.78,  4115.93,  "267.27",    "CEA",  "no",
      "RT 4 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "CEA",  "no",
      "RT 2 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "CEA",  "no",
     "RT 90 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "CEA",  "no",
     "RT 60 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "CEA",  "no",
     "RT 30 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "CEA",  "no",
  "Week2  ¯20oC",     "44523",   9139L, "ST",    77.2,    5.02,    40.5,  160.3,  71409.8,  1246.2,  3422.39,  4157.53,  "267.02",    "CEA",  "no",
  "Week2  ¯80oC",     "44523",   9139L, "ST",    77.2,    5.02,    27.8,    178,  71102.3, 1215.62,  3436.21,  4198.65,  "253.64",    "CEA",  "no",
  "Week4  ¯20oC",     "44538",   9139L, "AD",    90.7,     6.8,    91.3,  317.3,    59678,  874.57,  2896.25,  3521.96,  "142.48",    "CEA",  "no",
  "Week4  ¯80oC",     "44538",   9139L, "AD",    90.7,     6.8,      74,  281.8,  63738.3,  983.08,  3136.61,  3791.28,  "169.96",    "CEA",  "no",
  "Week9  ¯20oC",     "44572",   9139L, "ST",    97.3,    6.24,    45.5,  190.7,  83377.7, 1237.65,  3376.17,  3993.63,  "261.44",    "CEA",  "no",
  "Week9  ¯80oC",     "44572",   9139L, "ST",    97.3,    6.24,    47.2,  172.2,  77621.5, 1329.82,  3729.84,  4438.81,  "270.94",    "CEA",  "no",
         "Day 0",     "44509",   9139L, "ST",      73,    8.09,    41.3,  191.8,    71764, 1226.54,  3488.12,  4188.67,  "274.65",    "CEA", "yes",
         "Day 0",     "44509",   9139L, "AD",    70.2,    6.75,    78.3,  263.8,  63442.3, 1035.05,  3202.43,  4045.58,  "191.34",    "CEA", "yes",
         "Day 0",     "44509",   9139L, "JH",    78.3,    6.68,   113.7,  437.2,   109741, 1208.64,  3583.54,  4250.03,  "213.17",    "CEA", "yes",
  "Week1  ¯20oC",     "44517",   9139L, "ST",      83,    8.78,    50.8,  146.3,    73951, 1156.86,  3104.98,   3775.7,  "269.49",    "CEA", "yes",
  "Week1  ¯80oC",     "44517",   9139L, "ST",      83,    8.78,    50.5,  188.5,    75187, 1036.17,  2847.76,  3479.47,  "233.99",    "CEA", "yes",
      "RT 4 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "CEA", "yes",
      "RT 2 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "CEA", "yes",
     "RT 90 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "CEA", "yes",
     "RT 60 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "CEA", "yes",
     "RT 30 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "CEA", "yes",
  "Week2  ¯20oC",     "44523",   9139L, "ST",    77.2,    5.02,    40.8,  180.5,  83525.3, 1047.09,  2867.39,  3481.63,  "226.98",    "CEA", "yes",
  "Week2  ¯80oC",     "44523",   9139L, "ST",    77.2,    5.02,    38.8,  165.8,    80415, 1136.44,  3108.22,  3773.06,  "246.44",    "CEA", "yes",
  "Week4  ¯20oC",     "44538",   9139L, "AD",    90.7,     6.8,   101.3,  278.5,    69457,  829.82,  2582.83,  3125.81,  "155.19",    "CEA", "yes",
  "Week4  ¯80oC",     "44538",   9139L, "AD",    90.7,     6.8,    81.3,  326.5,  70477.8,  831.48,  2724.01,   3308.1,  "140.36",    "CEA", "yes",
  "Week9  ¯20oC",     "44572",   9139L, "ST",    97.3,    6.24,    51.7,  203.5,  92696.2, 1102.73,   2984.2,  3525.21,  "235.57",    "CEA", "yes",
  "Week9  ¯80oC",     "44572",   9139L, "ST",    97.3,    6.24,      29,    193,  86795.2, 1174.22,  3204.69,  3792.01,  "252.04",    "CEA", "yes",
         "Day 0",     "44509",   9139L, "ST",     159,    6.19,    24.5,   89.5,  36894.5,  1908.8,  3542.01,  4122.62, "1168.29",    "TNC",  "no",
         "Day 0",     "44509",   9139L, "AD",   149.1,   10.19,    26.9,  103.7,  35759.2,  2141.5,  4076.71,  4784.72, "1291.49",    "TNC",  "no",
         "Day 0",     "44509",   9139L, "JH",   215.8,   15.07,      51,  177.5,  55326.2, 2136.77,   3861.8,  4368.44, "1318.99",    "TNC",  "no",
  "Week1  ¯20oC",     "44517",   9139L, "ST",   155.2,       8,    24.6,   80.3,  34601.8, 2285.97,  4172.12,  5070.95,  "1420.7",    "TNC",  "no",
  "Week1  ¯80oC",     "44517",   9139L, "ST",   155.2,       8,    21.8,   81.3,  37015.6, 2276.37,  3970.95,  4608.77, "1401.21",    "TNC",  "no",
      "RT 4 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "TNC",  "no",
      "RT 2 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "TNC",  "no",
     "RT 90 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "TNC",  "no",
     "RT 60 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "TNC",  "no",
     "RT 30 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "TNC",  "no",
  "Week2  ¯20oC",     "44523",   9139L, "ST",   151.2,    6.98,    11.3,   61.3,  39410.3, 2329.66,  4099.19,  4568.39, "1570.17",    "TNC",  "no",
  "Week2  ¯80oC",     "44523",   9139L, "ST",   151.2,    6.98,    20.3,   72.5,  39746.8, 2305.88,  4296.15,  4937.32,  "1543.6",    "TNC",  "no",
  "Week4  ¯20oC",     "44538",   9139L, "AD",   149.2,    8.12,      29,  148.5,  34894.5, 1962.75,  4035.17,  4605.65, "1203.09",    "TNC",  "no",
  "Week4  ¯80oC",     "44538",   9139L, "AD",   149.2,    8.12,    29.8,  111.3,  36402.3, 1980.48,  4185.03,  4903.97, "1232.87",    "TNC",  "no",
  "Week9  ¯20oC",     "44572",   9139L, "ST",   153.5,    6.14,       9,   77.5,  41885.3, 2227.63,  3889.06,  4508.38, "1385.32",    "TNC",  "no",
  "Week9  ¯80oC",     "44572",   9139L, "ST",   153.5,    6.14,    10.8,     70,  39756.3, 2419.18,  4436.35,  5269.77, "1486.73",    "TNC",  "no",
         "Day 0",     "44509",   9139L, "ST",     159,    6.19,       2,   74.5,  36354.5, 2397.01,   4292.6,  4872.56, "1475.35",    "TNC", "yes",
         "Day 0",     "44509",   9139L, "AD",   149.1,   10.19,    21.4,   93.9,    32440, 2115.15,  4220.73,  5051.52,    "1270",    "TNC", "yes",
         "Day 0",     "44509",   9139L, "JH",   215.8,   15.07,    36.5,  161.2,  55808.2, 2324.67,  4160.48,   4700.6,  "1454.2",    "TNC", "yes",
  "Week1  ¯20oC",     "44517",   9139L, "ST",   155.2,       8,    27.8,   48.3,  35901.8, 2599.96,  4381.01,  5101.81, "1668.44",    "TNC", "yes",
  "Week1  ¯80oC",     "44517",   9139L, "ST",   155.2,       8,    10.8,   56.1,  37236.1, 2455.92,  4246.67,  4917.06, "1523.95",    "TNC", "yes",
      "RT 4 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "TNC", "yes",
      "RT 2 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "TNC", "yes",
     "RT 90 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "TNC", "yes",
     "RT 60 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "TNC", "yes",
     "RT 30 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "TNC", "yes",
  "Week2  ¯20oC",     "44523",   9139L, "ST",   151.2,    6.98,     8.8,   44.8,  40350.3, 2337.43,  4220.47,  4796.02, "1580.74",    "TNC", "yes",
  "Week2  ¯80oC",     "44523",   9139L, "ST",   151.2,    6.98,     9.5,   50.5,  38511.3, 2581.21,  4591.41,  5162.43, "1737.17",    "TNC", "yes",
  "Week4  ¯20oC",     "44538",   9139L, "AD",   149.2,    8.12,    55.8,  101.8,  35369.8, 2042.99,  4794.73,  5787.36, "1248.83",    "TNC", "yes",
  "Week4  ¯80oC",     "44538",   9139L, "AD",   149.2,    8.12,    35.5,  123.5,  34685.5, 2180.54,  4452.25,  5076.64, "1342.61",    "TNC", "yes",
  "Week9  ¯20oC",     "44572",   9139L, "ST",   153.5,    6.14,    15.8,   65.8,  42651.8, 2296.77,  4106.22,     4825, "1435.83",    "TNC", "yes",
  "Week9  ¯80oC",     "44572",   9139L, "ST",   153.5,    6.14,     9.5,     58,  40104.5, 2465.08,  4501.07,  5348.17, "1532.08",    "TNC", "yes",
         "Day 0",     "44509",   9139L, "ST",    67.7,    3.81,    40.3,  233.3,    64559, 5722.64, 16216.01, 19058.39, "1916.25",    "HE4",  "no",
         "Day 0",     "44509",   9139L, "AD",    67.2,    6.18,    56.8,  246.6,  55550.3,  5612.9, 17030.25, 21278.67, "1830.66",    "HE4",  "no",
         "Day 0",     "44509",   9139L, "JH",    73.4,    6.08,    67.1,  314.3,  80412.6, 5640.17, 17161.19, 18817.68, "1974.99",    "HE4",  "no",
  "Week1  ¯20oC",     "44517",   9139L, "ST",      69,    4.04,    30.8,    163,    63770, 6405.79, 17814.69,  21653.9, "2313.75",    "HE4",  "no",
  "Week1  ¯80oC",     "44517",   9139L, "ST",      69,    4.04,      44,    188,  65574.8, 6618.36, 17457.08, 20864.88, "2355.73",    "HE4",  "no",
      "RT 4 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "HE4",  "no",
      "RT 2 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "HE4",  "no",
     "RT 90 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "HE4",  "no",
     "RT 60 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "HE4",  "no",
     "RT 30 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "HE4",  "no",
  "Week2  ¯20oC",     "44523",   9139L, "ST",    68.4,    4.25,    25.9,  158.9,  68842.1, 6662.76, 19211.34, 21834.94, "2486.63",    "HE4",  "no",
  "Week2  ¯80oC",     "44523",   9139L, "ST",    68.4,    4.25,    30.6,  176.4,  68610.1, 6494.82, 17928.34, 20298.62, "2462.37",    "HE4",  "no",
  "Week4  ¯20oC",     "44538",   9139L, "AD",    84.3,    6.45,    77.7,    382,  61059.5, 5516.31, 17789.29, 21163.01,    "1747",    "HE4",  "no",
  "Week4  ¯80oC",     "44538",   9139L, "AD",    84.3,    6.45,    73.5,  306.5,  63211.2, 5801.83, 17527.15, 20621.34, "1968.15",    "HE4",  "no",
  "Week9  ¯20oC",     "44572",   9139L, "ST",    68.3,    6.93,    27.7,  137.7,  66172.9, 6297.04, 17492.63, 20048.93, "2380.48",    "HE4",  "no",
  "Week9  ¯80oC",     "44572",   9139L, "ST",    68.3,    6.93,    32.7,  128.9,  64107.2, 6706.89, 19388.03, 22353.45, "2492.72",    "HE4",  "no",
         "Day 0",     "44509",   9139L, "ST",    67.7,    3.81,    41.8,  169.3,    63735, 6477.25, 17719.57, 20730.05, "2261.41",    "HE4", "yes",
         "Day 0",     "44509",   9139L, "AD",    67.2,    6.18,    57.5,  249.8,  54755.6, 5983.91, 17795.28, 22157.26,  "1946.8",    "HE4", "yes",
         "Day 0",     "44509",   9139L, "JH",    73.4,    6.08,    58.8,  279.3,  79443.6, 6582.45, 19315.58, 21101.84, "2334.19",    "HE4", "yes",
  "Week1  ¯20oC",     "44517",   9139L, "ST",      69,    4.04,    31.8,  134.8,  64199.3, 7594.19, 19187.78, 22787.36, "2825.03",    "HE4", "yes",
  "Week1  ¯80oC",     "44517",   9139L, "ST",      69,    4.04,      25,  146.8,  64164.5, 6904.45, 18764.62, 22613.67, "2481.95",    "HE4", "yes",
      "RT 4 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "HE4", "yes",
      "RT 2 hrs",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "HE4", "yes",
     "RT 90 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "HE4", "yes",
     "RT 60 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "HE4", "yes",
     "RT 30 min",     "44518",   9139L, "JH",      NA,      NA,      NA,     NA,       NA,      NA,       NA,       NA,        NA,    "HE4", "yes",
  "Week2  ¯20oC",     "44523",   9139L, "ST",    68.4,    4.25,    28.9,  132.4,  70646.9, 6803.77, 19350.82, 21902.99, "2582.72",    "HE4", "yes",
  "Week2  ¯80oC",     "44523",   9139L, "ST",    68.4,    4.25,    17.6,  124.9,  67252.1, 7481.06, 21302.08, 24188.15, "2837.68",    "HE4", "yes",
  "Week4  ¯20oC",     "44538",   9139L, "AD",    84.3,    6.45,    55.7,  248.5,  62283.2, 6355.27, 20962.27, 24848.97, "2089.24",    "HE4", "yes",
  "Week4  ¯80oC",     "44538",   9139L, "AD",    84.3,    6.45,    62.7,  328.2,  61256.7, 6455.36, 20435.44, 24120.89, "2050.63",    "HE4", "yes",
  "Week9  ¯20oC",     "44572",   9139L, "ST",    68.3,    6.93,    26.7,  121.9,  67838.2, 6627.52, 17554.52, 19947.79, "2567.77",    "HE4", "yes",
  "Week9  ¯80oC",     "44572",   9139L, "ST",    68.3,    6.93,    19.2,  107.2,  64455.7, 7391.38,  20198.5,  23090.4, "2826.09",    "HE4", "yes"
  )

```


```{r}
clean_data <- stability_dye %>% 
  janitor::clean_names() %>% 
  filter(!grepl("RT", time_point)) 
```


## Data   

Data received from RDS  

*Showing first few rows*   
```{r}
head(clean_data)
```


###  Standards MFIs   

We average over operator in this case - we want to assess the overall affect the dye could have.  Since we have the data for the timepoints, we can plot that out as well.   

```{r}
clean_data %>% 
  #filter(time_point == "Day 0") %>% 
  group_by(time_point, assay, dye) %>% 
  summarise(s1 = mean(s1)) %>% 
  ggplot(.,aes(time_point, s1)) + 
  geom_point(aes(color = dye)) + 
  facet_wrap(vars(assay)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) + 
  labs(title = "Standard 1 MFI")


clean_data %>% 
  group_by(time_point, assay, dye) %>% 
  summarise(s5 = mean(s5)) %>% 
  ggplot(.,aes(time_point, s5)) + 
  geom_point(aes(color = dye)) + 
  facet_wrap(vars(assay)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) + 
  labs(title = "Standard 5 MFI")

clean_data %>% 
  group_by(time_point, assay, dye) %>% 
  summarise(s6 = mean(s6)) %>% 
  ggplot(.,aes(time_point, s6)) + 
  geom_point(aes(color = dye)) + 
  facet_wrap(vars(assay)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) + 
  labs(title = "Standard 6 MFI")

```




### Control Concentrations   

```{r}
clean_data %>% 
  filter(assay != "HE4" & assay != "IL1R2") %>% 
  filter(assay != "IL-8" & assay != "FLT3L") %>% 
  group_by(time_point, assay, dye) %>% 
  summarise(ctl_low = mean(ctl_low)) %>% 
  ggplot(.,aes(time_point, ctl_low)) + 
  geom_point(aes(color = dye)) + 
  facet_wrap(vars(assay)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) + 
  labs(title = "Low Control", 
       subtitle = "Concentration Units specific to each marker")


clean_data %>% 
  #filter(assay == "HE4" | assay == "IL1R2") %>% 
  filter(assay == "IL-8" | assay == "FLT3L") %>% 
  group_by(time_point, assay, dye) %>% 
  summarise(ctl_low = mean(ctl_low)) %>% 
  ggplot(.,aes(time_point, ctl_low)) + 
  geom_point(aes(color = dye)) + 
  facet_wrap(vars(assay)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) + 
  labs(title = "Low Control", 
       subtitle = "Concentration Units specific to each marker")


clean_data %>% 
  filter(assay != "HE4" & assay != "IL1R2") %>% 
  filter(assay != "IL-8" & assay != "FLT3L") %>% 
  group_by(time_point, assay, dye) %>% 
  summarise(ctl_mid = mean(ctl_mid)) %>% 
  ggplot(.,aes(time_point, ctl_mid)) + 
  geom_point(aes(color = dye)) + 
  facet_wrap(vars(assay)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) + 
  labs(title = "Mid Control", 
       subtitle = "Concentration Units specific to each marker")


clean_data %>% 
  #filter(assay == "HE4" | assay == "IL1R2") %>% 
  filter(assay == "IL-8" | assay == "FLT3L") %>% 
  group_by(time_point, assay, dye) %>% 
  summarise(ctl_low = mean(ctl_low)) %>% 
  ggplot(.,aes(time_point, ctl_low)) + 
  geom_point(aes(color = dye)) + 
  facet_wrap(vars(assay)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) + 
  labs(title = "Mid Control", 
       subtitle = "Concentration Units specific to each marker")








clean_data %>% 
  filter(assay != "HE4" & assay != "IL1R2") %>% 
  filter(assay != "IL-8" & assay != "FLT3L") %>% 
  group_by(time_point, assay, dye) %>% 
  summarise(ctr_high = mean(ctr_high)) %>% 
  ggplot(.,aes(time_point, ctr_high)) + 
  geom_point(aes(color = dye)) + 
  facet_wrap(vars(assay)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) + 
  labs(title = "High Control", 
       subtitle = "Concentration Units specific to each marker")


clean_data %>% 
  #filter(assay == "HE4" | assay == "IL1R2") %>% 
  filter(assay == "IL-8" | assay == "FLT3L") %>% 
  group_by(time_point, assay, dye) %>% 
  summarise(ctr_high = mean(ctr_high)) %>% 
  ggplot(.,aes(time_point, ctr_high)) + 
  geom_point(aes(color = dye)) + 
  facet_wrap(vars(assay)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) + 
  labs(title = "High Control", 
       subtitle = "Concentration Units specific to each marker")










clean_data %>% 
  filter(assay != "HE4" & assay != "IL1R2") %>% 
  filter(assay != "IL-8" & assay != "FLT3L") %>% 
  group_by(time_point, assay, dye) %>% 
  mutate(nat_ctrl = as.double(nat_ctrl)) %>% 
  summarise(nat_ctrl = mean(nat_ctrl)) %>% 
  ggplot(.,aes(time_point, nat_ctrl)) + 
  geom_point(aes(color = dye)) + 
  facet_wrap(vars(assay)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) + 
  labs(title = "Natural Control", 
       subtitle = "Concentration Units specific to each marker")


clean_data %>% 
  filter(assay == "HE4" | assay == "IL1R2") %>% 
  #filter(assay == "IL-8" | assay == "FLT3L") %>% 
  group_by(time_point, assay, dye) %>% 
  mutate(nat_ctrl = as.double(nat_ctrl)) %>% 
  summarise(nat_ctrl = mean(nat_ctrl)) %>% 
  ggplot(.,aes(time_point, nat_ctrl)) + 
  geom_point(aes(color = dye)) + 
  facet_wrap(vars(assay)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10)) + 
  labs(title = "Natural Control", 
       subtitle = "Concentration Units specific to each marker")
```







